---

version: "{build}"

install:
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --no-document --system
  - gem install bundler --no-document
  - bundle install --jobs 3 --retry 3

build: off

# We are intentionally starting Rake a few times here, because we have seen some
# encoding issues when all tasks are run in just one process (`rake default`).
test_script:
  - bundle exec rake spec
  - bundle exec rake ascii_spec
  - bundle exec rake internal_investigation

environment:
  matrix:
    - ruby_version: '25'
    - ruby_version: 25-x64
